# Generated by Django 4.1 on 2023-05-10 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_proveedor", models.CharField(max_length=264)),
                ("dir_proveedor", models.CharField(max_length=264)),
                ("cont_nom_proveedor", models.CharField(max_length=264)),
                ("cont_tel_proveedor", models.CharField(max_length=264)),
                ("cont_mai_proveedor", models.EmailField(max_length=264)),
                ("com_proveedor", models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name="TipoProveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_tipoproveedor", models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name="TipoSuministro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_tiposuministro", models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name="Suministro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku_suministro", models.CharField(max_length=264)),
                ("nom_suministro", models.CharField(max_length=264)),
                (
                    "prov_suministro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="suministro_app.proveedor",
                    ),
                ),
                (
                    "tip_suministro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="suministro_app.tiposuministro",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="proveedor",
            name="tip_proveedor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="suministro_app.tipoproveedor",
            ),
        ),
        migrations.CreateModel(
            name="Equipos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_equipo", models.CharField(max_length=264)),
                ("fabr_equipo", models.CharField(max_length=264)),
                ("ser_equipo", models.CharField(max_length=264)),
                ("fec_adqui_equipo", models.DateField()),
                ("vida_equipo", models.IntegerField()),
                (
                    "est_equipo",
                    models.CharField(
                        choices=[
                            ("AC", "Activo"),
                            ("MA", "Mantenimiento"),
                            ("RE", "Reparacion"),
                            ("FS", "Fuera de Servicio"),
                        ],
                        default="AC",
                        max_length=2,
                    ),
                ),
                ("ubi_equipo", models.CharField(max_length=264)),
                ("gar_equipo", models.IntegerField()),
                (
                    "prov_equipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="suministro_app.proveedor",
                    ),
                ),
            ],
        ),
    ]
