# Generated by Django 4.1 on 2023-05-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suministro_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="proveedor",
            name="nif_proveedor",
            field=models.CharField(default="", max_length=9),
            preserve_default=False,
        ),
    ]
