# Generated by Django 4.1 on 2023-09-04 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suministro_app", "0002_proveedor_nif_proveedor"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipos",
            name="potencia_equipo",
            field=models.FloatField(default=0),
        ),
    ]
