# Generated by Django 4.1 on 2023-09-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suministro_app", "0003_equipos_potencia_equipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proveedor",
            name="com_proveedor",
            field=models.CharField(max_length=264, null=True),
        ),
    ]
