# Generated by Django 4.1 on 2023-09-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suministro_app", "0004_alter_proveedor_com_proveedor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proveedor",
            name="com_proveedor",
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
    ]
