# Generated by Django 4.1 on 2023-09-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suministro_app", "0005_alter_proveedor_com_proveedor"),
    ]

    operations = [
        migrations.AddField(
            model_name="suministro",
            name="unidad_suministro",
            field=models.CharField(
                choices=[
                    ("KG", "kg"),
                    ("M3", "m³"),
                    ("L", "L"),
                    ("M", "m"),
                    ("M2", "m²"),
                    ("UN", "unidad"),
                ],
                default="KG",
                max_length=2,
            ),
        ),
    ]
