# Generated by Django 4.1 on 2023-05-04 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Rol",
            fields=[
                ("id_rol", models.AutoField(primary_key=True, serialize=False)),
                ("nom_rol", models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_mail", models.CharField(max_length=264)),
                ("user_name", models.CharField(max_length=264)),
                ("user_lastname", models.CharField(max_length=264)),
                ("user_rol", models.CharField(max_length=264)),
                ("user_phone", models.CharField(max_length=264)),
                ("user_state", models.BooleanField()),
                ("user_lastLogin", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="RolxUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_rol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="prueba_app.rol"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prueba_app.usuario",
                    ),
                ),
            ],
        ),
    ]
