# Generated by Django 4.1 on 2023-09-25 00:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cadena_app", "0041_alter_midpointemision_plancadena_tipo_midpoint"),
        ("producto_app", "0003_alter_producto_fec_crea_producto"),
        ("suministro_app", "0005_alter_proveedor_com_proveedor"),
    ]

    operations = [
        migrations.CreateModel(
            name="Actividad_Orden",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_actividad",
                    models.CharField(
                        choices=[("PR", "Productiva"), ("EN", "Envio")],
                        default="PR",
                        max_length=2,
                    ),
                ),
                ("nom_actividad", models.CharField(max_length=264, null=True)),
                ("tiempo_equipo_asociado", models.FloatField()),
                (
                    "equipo_asociado",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="suministro_app.equipos",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ActividadEmision_Orden",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad_sustancia", models.FloatField()),
                (
                    "actividadorden_asociado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produccion_app.actividad_orden",
                    ),
                ),
                (
                    "sustancia_asociada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadena_app.sustancia_emision",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DetalleOrdenVenta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad_detalle", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="OrdenEntrega",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("direccion_entrega", models.CharField(max_length=264)),
                ("fecha_entrega", models.DateField(default=datetime.date.today)),
                ("contacto_entrega", models.CharField(max_length=264)),
                ("observaciones_entrega", models.CharField(max_length=264)),
                (
                    "estado_entrega",
                    models.CharField(
                        choices=[
                            ("RE", "Registrado"),
                            ("PR", "Preparando"),
                            ("ON", "Enviado"),
                            ("EN", "Enviado"),
                            ("CA", "Cancelado"),
                        ],
                        default="RE",
                        max_length=2,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrdenProduccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_orden", models.DateField(default=datetime.date.today)),
                (
                    "estado_produccion",
                    models.CharField(
                        choices=[
                            ("RE", "Registrado"),
                            ("PR", "En Proceso"),
                            ("CO", "Completado"),
                            ("CA", "Cancelado"),
                        ],
                        default="RE",
                        max_length=2,
                    ),
                ),
                (
                    "orden_venta_detalle",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produccion_app.detalleordenventa",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrdenSuministro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad_suministro", models.FloatField()),
                (
                    "estado_pedido_suministro",
                    models.CharField(
                        choices=[
                            ("RE", "Pedido"),
                            ("PR", "En Proceso"),
                            ("CO", "Completado"),
                            ("CA", "Cancelado"),
                        ],
                        default="RE",
                        max_length=2,
                    ),
                ),
                (
                    "orden_produccion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produccion_app.ordenproduccion",
                    ),
                ),
                (
                    "suministro_asociado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="suministro_app.suministro",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrdenVenta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cod_venta", models.CharField(max_length=50)),
                ("fech_venta", models.DateField(default=datetime.date.today)),
                ("cliente_venta", models.CharField(max_length=264)),
                ("direccion_venta", models.CharField(max_length=264)),
                ("fecha_entrega_venta", models.DateField(default=datetime.date.today)),
                (
                    "estado_venta",
                    models.CharField(
                        choices=[
                            ("RE", "Registrado"),
                            ("SU", "Soli. Suministro"),
                            ("PR", "En Producción"),
                            ("OE", "Preparando Envio"),
                            ("LE", "Enviado"),
                            ("EN", "Completado"),
                            ("CA", "Cancelado"),
                        ],
                        default="RE",
                        max_length=2,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tramos_Orden",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descripcion_tramoexterno",
                    models.CharField(max_length=264, null=True),
                ),
                ("km_tramoexterno", models.FloatField()),
                (
                    "energia_tramoexterno",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadena_app.energia_transporte",
                    ),
                ),
                (
                    "orden_envio_asociada",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produccion_app.ordenentrega",
                    ),
                ),
                (
                    "tipo_tramoexterno",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadena_app.tipo_transporte",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SuministroTramos_Orden",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion_tramo", models.CharField(max_length=264, null=True)),
                ("km_tramo", models.FloatField()),
                (
                    "energia_tramo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadena_app.energia_transporte",
                    ),
                ),
                (
                    "ordensuministro_asociado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produccion_app.ordensuministro",
                    ),
                ),
                (
                    "tipo_tramo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadena_app.tipo_transporte",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SuministroEmision_Orden",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad_sustancia", models.FloatField()),
                (
                    "ordensuministro_asociado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produccion_app.ordensuministro",
                    ),
                ),
                (
                    "sustancia_asociada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadena_app.sustancia_emision",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProduccionCalculosEndpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor_real", models.FloatField()),
                ("valor_pla", models.FloatField()),
                (
                    "cadena_asociada",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produccion_app.ordenproduccion",
                    ),
                ),
                (
                    "midpoint_endpoint",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadena_app.endpoint",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ordenentrega",
            name="orden_venta_entrega",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="produccion_app.ordenventa",
            ),
        ),
        migrations.CreateModel(
            name="MidpointEmision_Orden",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_midpoint",
                    models.CharField(
                        choices=[
                            ("TS", "Tramo Sumininstro"),
                            ("TI", "Tierra"),
                            ("SU", "Suministro"),
                            ("TR", "Tramos"),
                            ("AC", "Actividades"),
                            ("CE", "Consumo de Equipo"),
                        ],
                        default="SU",
                        max_length=2,
                    ),
                ),
                ("points_midpoint", models.FloatField()),
                (
                    "actividad_asociada",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produccion_app.actividad_orden",
                    ),
                ),
                (
                    "actividademision_asociado",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produccion_app.actividademision_orden",
                    ),
                ),
                (
                    "suministroEmision_asociado",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produccion_app.suministroemision_orden",
                    ),
                ),
                (
                    "suministroTramos_asociado",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produccion_app.suministrotramos_orden",
                    ),
                ),
                (
                    "sustancia_midpoint_asociado",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadena_app.sustancia_midpoint_emision",
                    ),
                ),
                (
                    "tramos_envio",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produccion_app.tramos_orden",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="detalleordenventa",
            name="orden_venta_detalle",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="produccion_app.ordenventa",
            ),
        ),
        migrations.AddField(
            model_name="detalleordenventa",
            name="producto_detalle",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="producto_app.producto"
            ),
        ),
        migrations.AddField(
            model_name="actividad_orden",
            name="produccion_asociada",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="produccion_app.ordenproduccion",
            ),
        ),
    ]
