# Generated by Django 4.1 on 2023-09-25 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("producto_app", "0003_alter_producto_fec_crea_producto"),
        ("produccion_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detalleordenventa",
            name="producto_detalle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="producto_app.producto"
            ),
        ),
        migrations.AlterField(
            model_name="ordenventa",
            name="fecha_entrega_venta",
            field=models.DateField(),
        ),
    ]
