# Generated by Django 4.1 on 2023-09-27 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cadena_app", "0041_alter_midpointemision_plancadena_tipo_midpoint"),
        ("produccion_app", "0002_alter_detalleordenventa_producto_detalle_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordenproduccion",
            name="fuente_energia",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cadena_app.fuenteenergia",
            ),
        ),
        migrations.AddField(
            model_name="ordenproduccion",
            name="tierra_m2",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="ordenproduccion",
            name="tierra_ocupada",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cadena_app.midpointtierra",
            ),
        ),
        migrations.AlterField(
            model_name="ordensuministro",
            name="estado_pedido_suministro",
            field=models.CharField(
                choices=[
                    ("RE", "Registrado"),
                    ("PE", "Pedido"),
                    ("CO", "Completado"),
                    ("CA", "Cancelado"),
                ],
                default="RE",
                max_length=2,
            ),
        ),
    ]
