# Generated by Django 4.1 on 2023-09-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produccion_app", "0003_ordenproduccion_fuente_energia_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="actividad_orden",
            name="tipo_actividad",
        ),
        migrations.AddField(
            model_name="actividad_orden",
            name="estado_actividad",
            field=models.CharField(
                choices=[
                    ("PL", "Planificado"),
                    ("EN", "En ejecución"),
                    ("CE", "Cerrado"),
                ],
                default="PL",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="ordenventa",
            name="estado_venta",
            field=models.CharField(
                choices=[
                    ("RE", "Registrado"),
                    ("PR", "En Producción"),
                    ("OE", "Preparando Envio"),
                    ("LE", "Enviado"),
                    ("EN", "Completado"),
                    ("CA", "Cancelado"),
                ],
                default="RE",
                max_length=2,
            ),
        ),
    ]
