# Generated by Django 4.1 on 2023-10-01 16:51

import datetime
from django.db import migrations, models
import produccion_app.models


class Migration(migrations.Migration):

    dependencies = [
        ("produccion_app", "0005_alter_actividad_orden_estado_actividad_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordenentrega",
            name="fecha_entrega",
            field=models.DateField(
                default=datetime.date.today,
            ),
        ),
    ]
