# Generated by Django 4.1 on 2023-10-01 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("produccion_app", "0007_actividad_envio_actividademision_envio"),
    ]

    operations = [
        migrations.RenameField(
            model_name="actividad_envio",
            old_name="produccion_asociada",
            new_name="entrega_asociada",
        ),
        migrations.RenameField(
            model_name="actividademision_envio",
            old_name="actividadorden_asociado",
            new_name="actividadenvio_asociado",
        ),
    ]
