# Generated by Django 4.1 on 2023-10-01 19:13

import datetime
from django.db import migrations, models
import produccion_app.models


class Migration(migrations.Migration):

    dependencies = [
        (
            "produccion_app",
            "0008_rename_produccion_asociada_actividad_envio_entrega_asociada_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordenentrega",
            name="contacto_entrega",
            field=models.CharField(max_length=264, null=True),
        ),
        migrations.AlterField(
            model_name="ordenentrega",
            name="direccion_entrega",
            field=models.CharField(max_length=264, null=True),
        ),
        migrations.AlterField(
            model_name="ordenentrega",
            name="fecha_entrega",
            field=models.DateField(
                default=datetime.date.today,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="ordenentrega",
            name="observaciones_entrega",
            field=models.CharField(max_length=264, null=True),
        ),
    ]
