# Generated by Django 4.1 on 2023-10-01 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produccion_app", "0009_alter_ordenentrega_contacto_entrega_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordenentrega",
            name="estado_entrega",
            field=models.CharField(
                choices=[
                    ("RE", "Registrado"),
                    ("PR", "Preparando"),
                    ("ON", "Enviado"),
                    ("CO", "Completado"),
                    ("CA", "Cancelado"),
                ],
                default="RE",
                max_length=2,
            ),
        ),
    ]
