# Generated by Django 4.1 on 2023-10-02 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cadena_app", "0041_alter_midpointemision_plancadena_tipo_midpoint"),
        ("produccion_app", "0010_alter_ordenentrega_estado_entrega"),
    ]

    operations = [
        migrations.RenameField(
            model_name="produccioncalculosendpoint",
            old_name="cadena_asociada",
            new_name="orden_asociada",
        ),
        migrations.CreateModel(
            name="EnvioCalculosEndpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor_real", models.FloatField()),
                ("valor_pla", models.FloatField()),
                (
                    "envio_asociada",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produccion_app.ordenproduccion",
                    ),
                ),
                (
                    "midpoint_endpoint",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadena_app.endpoint",
                    ),
                ),
            ],
        ),
    ]
