# Generated by Django 4.1 on 2023-10-02 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "produccion_app",
            "0011_rename_cadena_asociada_produccioncalculosendpoint_orden_asociada_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="midpointemision_orden",
            name="orden_asociada",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="produccion_app.ordenproduccion",
            ),
        ),
    ]
