# Generated by Django 4.1 on 2023-10-02 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cadena_app", "0041_alter_midpointemision_plancadena_tipo_midpoint"),
        ("produccion_app", "0012_midpointemision_orden_orden_asociada"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enviocalculosendpoint",
            name="envio_asociada",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="produccion_app.ordenentrega",
            ),
        ),
        migrations.CreateModel(
            name="MidpointEmision_Entrega",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_midpoint",
                    models.CharField(
                        choices=[
                            ("TR", "Tramos"),
                            ("AC", "Actividades"),
                            ("CE", "Consumo de Equipo"),
                        ],
                        default="TR",
                        max_length=2,
                    ),
                ),
                ("points_midpoint", models.FloatField()),
                (
                    "actividad_asociada",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produccion_app.actividad_orden",
                    ),
                ),
                (
                    "actividademision_asociado",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produccion_app.actividademision_envio",
                    ),
                ),
                (
                    "orden_asociada",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produccion_app.ordenentrega",
                    ),
                ),
                (
                    "sustancia_midpoint_asociado",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadena_app.sustancia_midpoint_emision",
                    ),
                ),
                (
                    "tramos_envio",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produccion_app.tramos_orden",
                    ),
                ),
            ],
        ),
    ]
