# Generated by Django 4.1 on 2023-10-07 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("suministro_app", "0006_suministro_unidad_suministro"),
        ("produccion_app", "0015_ordenentrega_fuente_energia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actividad_envio",
            name="equipo_asociado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="suministro_app.equipos",
            ),
        ),
        migrations.AlterField(
            model_name="actividad_orden",
            name="equipo_asociado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="suministro_app.equipos",
            ),
        ),
    ]
