# Generated by Django 4.1 on 2023-10-15 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produccion_app", "0016_alter_actividad_envio_equipo_asociado_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordenentrega",
            name="observaciones_entrega",
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
    ]
