# Generated by Django 4.1 on 2023-07-24 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("producto_app", "0003_alter_producto_fec_crea_producto"),
    ]

    operations = [
        migrations.CreateModel(
            name="FuenteEnergia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_energia", models.CharField(max_length=264)),
                ("co2_energia", models.FloatField()),
                ("Nox_energia", models.FloatField()),
                ("so2_energia", models.FloatField()),
                ("h25_energia", models.FloatField()),
                ("pm_energia", models.FloatField()),
                ("co60_energia", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="MidpointTierra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_tipouso", models.CharField(max_length=264)),
                ("cfm_tipouso", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="CadenaSuministro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tierra_m2", models.FloatField()),
                (
                    "fuente_energia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadena_app.fuenteenergia",
                    ),
                ),
                (
                    "prod_asociado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="producto_app.producto",
                    ),
                ),
                (
                    "tierra_ocupada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadena_app.midpointtierra",
                    ),
                ),
            ],
        ),
    ]
