# Generated by Django 4.1 on 2023-07-31 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("producto_app", "0003_alter_producto_fec_crea_producto"),
        ("cadena_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cadenasuministro",
            name="prod_asociado",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="producto_app.producto"
            ),
        ),
    ]
