# Generated by Django 4.1 on 2023-07-31 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadena_app", "0002_alter_cadenasuministro_prod_asociado"),
    ]

    operations = [
        migrations.CreateModel(
            name="ElementosEmision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_emision",
                    models.CharField(
                        choices=[
                            ("AT", "Atmósfera"),
                            ("TI", "Tierra"),
                            ("AD", "Agua Dulce"),
                            ("AS", "Océ,anos"),
                            ("RF", "Recursos Fosiles"),
                            ("AU", "Oceanos"),
                        ],
                        default="AT",
                        max_length=2,
                    ),
                ),
                ("midpoint_emision", models.CharField(max_length=264)),
                ("componente_emision", models.CharField(max_length=264)),
                ("valor_emision", models.FloatField()),
            ],
        ),
    ]
