# Generated by Django 4.1 on 2023-07-31 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadena_app", "0004_alter_elementosemision_tipo_emision"),
    ]

    operations = [
        migrations.AddField(
            model_name="elementosemision",
            name="unidad_emision",
            field=models.CharField(default="Kg", max_length=264),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="elementosemision",
            name="valor_emision",
            field=models.FloatField(default="Kg"),
        ),
    ]
