# Generated by Django 4.1 on 2023-07-31 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cadena_app", "0005_elementosemision_unidad_emision_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Midpoint_emision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_midpoint", models.CharField(max_length=264)),
                ("nom_emision", models.CharField(max_length=264)),
            ],
        ),
        migrations.AlterField(
            model_name="elementosemision",
            name="midpoint_emision",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cadena_app.midpoint_emision",
            ),
        ),
    ]
