# Generated by Django 4.1 on 2023-08-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadena_app", "0008_sustancia_emision_delete_elemento_emision"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sustancia_emision",
            name="tipo_emision",
            field=models.CharField(
                choices=[
                    ("AT", "Atmósfera"),
                    ("TI", "Tierra"),
                    ("AD", "Agua Dulce"),
                    ("AS", "Océanos"),
                    ("RF", "Recursos Fosiles"),
                    ("AU", "Oceanos"),
                    ("CR", "Consumo Recursos"),
                ],
                default="AT",
                max_length=2,
            ),
        ),
    ]
