# Generated by Django 4.1 on 2023-08-01 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("suministro_app", "0002_proveedor_nif_proveedor"),
        ("cadena_app", "0009_alter_sustancia_emision_tipo_emision"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sustancia_emision",
            name="tipo_emision",
            field=models.CharField(
                choices=[
                    ("AT", "Atmósfera"),
                    ("TI", "Tierra"),
                    ("AD", "Agua Dulce"),
                    ("AS", "Océanos"),
                    ("RF", "Recursos Fosiles"),
                    ("CR", "Consumo Recursos"),
                ],
                default="AT",
                max_length=2,
            ),
        ),
        migrations.CreateModel(
            name="Suministro_PlanCadena",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad_sustancia", models.FloatField()),
                (
                    "suministro_asociado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="suministro_app.suministro",
                    ),
                ),
                (
                    "sustancia_asociada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadena_app.sustancia_emision",
                    ),
                ),
            ],
        ),
    ]
