# Generated by Django 4.1 on 2023-08-01 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cadena_app", "0010_alter_sustancia_emision_tipo_emision_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="suministro_plancadena",
            name="cadena_asociada",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cadena_app.cadenasuministro",
            ),
        ),
    ]
