# Generated by Django 4.1 on 2023-08-06 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cadena_app", "0011_suministro_plancadena_cadena_asociada"),
    ]

    operations = [
        migrations.RenameField(
            model_name="suministro_plancadena",
            old_name="cantidad_sustancia",
            new_name="cantidad_suministro",
        ),
        migrations.RemoveField(
            model_name="suministro_plancadena",
            name="sustancia_asociada",
        ),
        migrations.AddField(
            model_name="suministro_plancadena",
            name="unidad_suministro",
            field=models.CharField(
                choices=[
                    ("KG", "kg"),
                    ("M3", "m³"),
                    ("L", "L"),
                    ("M", "m"),
                    ("M2", "m²"),
                    ("UN", "unidad"),
                ],
                default="KG",
                max_length=2,
            ),
        ),
        migrations.CreateModel(
            name="SuministroEmision_PlanCadena",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad_sustancia", models.FloatField()),
                (
                    "sumcadena_asociado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadena_app.suministro_plancadena",
                    ),
                ),
                (
                    "sustancia_asociada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadena_app.sustancia_emision",
                    ),
                ),
            ],
        ),
    ]
