# Generated by Django 4.1 on 2023-08-19 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "cadena_app",
            "0012_rename_cantidad_sustancia_suministro_plancadena_cantidad_suministro_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Energia_transporte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_energiatransporte", models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name="Tipo_transporte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_transporte", models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name="TramosExternos_PlanCadena",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("km_tramoexterno", models.FloatField()),
                (
                    "cadena_asociada",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadena_app.cadenasuministro",
                    ),
                ),
                (
                    "energia_tramoexterno",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadena_app.energia_transporte",
                    ),
                ),
                (
                    "tipo_tramoexterno",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadena_app.tipo_transporte",
                    ),
                ),
            ],
        ),
    ]
