# Generated by Django 4.1 on 2023-08-20 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cadena_app", "0014_tramosexternos_plancadena_descripcion_tramoexterno"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tramos_PlanCadena",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_transporte",
                    models.CharField(
                        choices=[("IN", "Interno"), ("EX", "Externo")],
                        default="EX",
                        max_length=2,
                    ),
                ),
                (
                    "descripcion_tramoexterno",
                    models.CharField(max_length=264, null=True),
                ),
                ("km_tramoexterno", models.FloatField()),
                (
                    "cadena_asociada",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadena_app.cadenasuministro",
                    ),
                ),
                (
                    "energia_tramoexterno",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadena_app.energia_transporte",
                    ),
                ),
                (
                    "tipo_tramoexterno",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadena_app.tipo_transporte",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="TramosExternos_PlanCadena",
        ),
    ]
