# Generated by Django 4.1 on 2023-08-21 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("suministro_app", "0002_proveedor_nif_proveedor"),
        ("cadena_app", "0015_tramos_plancadena_delete_tramosexternos_plancadena"),
    ]

    operations = [
        migrations.CreateModel(
            name="Actividad_PlanCadena",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_actividad",
                    models.CharField(
                        choices=[("PR", "Productiva"), ("EN", "Envio")],
                        default="PR",
                        max_length=2,
                    ),
                ),
                ("tiempo_equipo_asociado", models.FloatField()),
                (
                    "cadena_asociada",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadena_app.cadenasuministro",
                    ),
                ),
                (
                    "equipo_asociado",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="suministro_app.equipos",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="tramos_plancadena",
            name="tipo_transporte",
            field=models.CharField(
                choices=[("IN", "Interno"), ("EX", "Suministro"), ("EN", "Envio")],
                default="EX",
                max_length=2,
            ),
        ),
        migrations.CreateModel(
            name="ActividadEmision_PlanCadena",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad_sustancia", models.FloatField()),
                (
                    "actividadplan_asociado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadena_app.actividad_plancadena",
                    ),
                ),
                (
                    "sustancia_asociada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadena_app.sustancia_emision",
                    ),
                ),
            ],
        ),
    ]
