# Generated by Django 4.1 on 2023-08-22 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cadena_app", "0017_actividad_plancadena_nom_actividad"),
    ]

    operations = [
        migrations.CreateModel(
            name="MidpointEmision_PlanCadena",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_midpoint",
                    models.CharField(
                        choices=[
                            ("TI", "Tierra"),
                            ("SU", "Suministro"),
                            ("TR", "Tramos"),
                            ("AC", "Actividades"),
                        ],
                        default="SU",
                        max_length=2,
                    ),
                ),
                ("points_midpoint", models.FloatField()),
                (
                    "cadena_asociada",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadena_app.cadenasuministro",
                    ),
                ),
                (
                    "midpoints_emision_asociada",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadena_app.midpoint_emision",
                    ),
                ),
            ],
        ),
    ]
