# Generated by Django 4.1 on 2023-08-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadena_app", "0018_midpointemision_plancadena"),
    ]

    operations = [
        migrations.AddField(
            model_name="midpointtierra",
            name="cfm_relax_tipouso",
            field=models.FloatField(null=True),
        ),
    ]
