# Generated by Django 4.1 on 2023-08-22 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadena_app", "0019_midpointtierra_cfm_relax_tipouso"),
    ]

    operations = [
        migrations.AlterField(
            model_name="midpointemision_plancadena",
            name="tipo_midpoint",
            field=models.CharField(
                choices=[
                    ("TO", "Tierra Ocupacion"),
                    ("TR", "Tierra Relax"),
                    ("SU", "Suministro"),
                    ("TR", "Tramos"),
                    ("AC", "Actividades"),
                ],
                default="SU",
                max_length=2,
            ),
        ),
    ]
