# Generated by Django 4.1 on 2023-08-22 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cadena_app", "0020_alter_midpointemision_plancadena_tipo_midpoint"),
    ]

    operations = [
        migrations.AddField(
            model_name="midpointemision_plancadena",
            name="suministroEmision_asociado",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cadena_app.suministroemision_plancadena",
            ),
        ),
    ]
