# Generated by Django 4.1 on 2023-08-26 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cadena_app", "0022_midpointemision_plancadena_tramos_plancadena_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MidpointTramos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("co2_tramo", models.FloatField()),
                ("nox_tramo", models.FloatField()),
                ("pm_tramo", models.FloatField()),
                (
                    "Tipo_transporte",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadena_app.tipo_transporte",
                    ),
                ),
                (
                    "energia_transporte",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadena_app.energia_transporte",
                    ),
                ),
            ],
        ),
    ]
