# Generated by Django 4.1 on 2023-09-03 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "cadena_app",
            "0024_rename_unidad_emision_sustancia_emision_categoria_emision_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria_emision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_categoria", models.CharField(max_length=264)),
            ],
        ),
        migrations.AddField(
            model_name="sustancia_emision",
            name="categoria_asociada",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cadena_app.categoria_emision",
            ),
        ),
    ]
