# Generated by Django 4.1 on 2023-09-03 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cadena_app", "0025_categoria_emision_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sustancia_emision",
            name="categoria_emision",
        ),
    ]
