# Generated by Django 4.1 on 2023-09-03 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cadena_app", "0026_remove_sustancia_emision_categoria_emision"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sustancia_emision",
            name="midpoint_emision",
        ),
        migrations.RemoveField(
            model_name="sustancia_emision",
            name="valor_emision",
        ),
        migrations.CreateModel(
            name="Sustancia_Midpoint_emision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor_emision", models.FloatField(default="0")),
                (
                    "midpoint_emision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadena_app.midpoint_emision",
                    ),
                ),
                (
                    "sustancia_emision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadena_app.sustancia_emision",
                    ),
                ),
            ],
        ),
    ]
