# Generated by Django 4.1 on 2023-09-04 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cadena_app", "0027_remove_sustancia_emision_midpoint_emision_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="midpointemision_plancadena",
            name="actividademision_asociado",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cadena_app.actividademision_plancadena",
            ),
        ),
        migrations.AlterField(
            model_name="midpointemision_plancadena",
            name="tipo_midpoint",
            field=models.CharField(
                choices=[
                    ("TO", "Tierra Ocupacion"),
                    ("TX", "Tierra Relax"),
                    ("SU", "Suministro"),
                    ("TN", "Tramos NOX"),
                    ("TR", "Tramos Otros"),
                    ("AC", "Actividades"),
                ],
                default="SU",
                max_length=2,
            ),
        ),
    ]
