# Generated by Django 4.1 on 2023-09-04 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "cadena_app",
            "0028_midpointemision_plancadena_actividademision_asociado_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="fuenteenergia",
            old_name="Nox_energia",
            new_name="nox_energia",
        ),
    ]
