# Generated by Django 4.1 on 2023-09-04 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cadena_app", "0030_midpointemision_plancadena_sustancia_midpoint_asociado"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fuenteenergia",
            name="h25_energia",
        ),
    ]
