# Generated by Django 4.1 on 2023-09-04 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cadena_app", "0031_remove_fuenteenergia_h25_energia"),
    ]

    operations = [
        migrations.AddField(
            model_name="midpointemision_plancadena",
            name="actividad_asociada",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cadena_app.actividad_plancadena",
            ),
        ),
        migrations.AlterField(
            model_name="midpointemision_plancadena",
            name="tipo_midpoint",
            field=models.CharField(
                choices=[
                    ("TO", "Tierra Ocupacion"),
                    ("TX", "Tierra Relax"),
                    ("SU", "Suministro"),
                    ("TN", "Tramos NOX"),
                    ("TR", "Tramos Otros"),
                    ("AC", "Actividades"),
                    ("CE", "Consumo de Equipo"),
                ],
                default="SU",
                max_length=2,
            ),
        ),
    ]
