# Generated by Django 4.1 on 2023-09-05 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadena_app", "0032_midpointemision_plancadena_actividad_asociada_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="midpointemision_plancadena",
            name="midpoints_emision_asociada",
        ),
        migrations.AlterField(
            model_name="midpointemision_plancadena",
            name="tipo_midpoint",
            field=models.CharField(
                choices=[
                    ("TI", "Tierra"),
                    ("SU", "Suministro"),
                    ("TR", "Tramos"),
                    ("AC", "Actividades"),
                    ("CE", "Consumo de Equipo"),
                ],
                default="SU",
                max_length=2,
            ),
        ),
    ]
