# Generated by Django 4.1 on 2023-09-06 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "cadena_app",
            "0034_calculosendpoint_endpoint_midpointendpointfactor_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CadenaCalculosEndpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor", models.FloatField()),
                (
                    "cadena_asociada",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadena_app.cadenasuministro",
                    ),
                ),
                (
                    "midpoint_endpoint",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadena_app.midpointendpointfactor",
                    ),
                ),
            ],
        ),
    ]
