# Generated by Django 4.1 on 2023-09-06 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cadena_app", "0035_cadenacalculosendpoint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cadenacalculosendpoint",
            name="midpoint_endpoint",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cadena_app.endpoint",
            ),
        ),
    ]
