# Generated by Django 4.1 on 2023-09-18 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cadena_app", "0036_alter_cadenacalculosendpoint_midpoint_endpoint"),
    ]

    operations = [
        migrations.CreateModel(
            name="SuministroTramos_PlanCadena",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descripcion_tramoexterno",
                    models.CharField(max_length=264, null=True),
                ),
                ("km_tramoexterno", models.FloatField()),
                (
                    "energia_tramoexterno",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadena_app.energia_transporte",
                    ),
                ),
                (
                    "sumcadena_asociado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadena_app.suministro_plancadena",
                    ),
                ),
            ],
        ),
    ]
