# Generated by Django 4.1 on 2023-09-18 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cadena_app", "0037_suministrotramos_plancadena"),
    ]

    operations = [
        migrations.RenameField(
            model_name="suministrotramos_plancadena",
            old_name="descripcion_tramoexterno",
            new_name="descripcion_tramo",
        ),
        migrations.RenameField(
            model_name="suministrotramos_plancadena",
            old_name="energia_tramoexterno",
            new_name="energia_tramo",
        ),
        migrations.RenameField(
            model_name="suministrotramos_plancadena",
            old_name="km_tramoexterno",
            new_name="km_tramo",
        ),
    ]
