# Generated by Django 4.1 on 2023-09-18 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "cadena_app",
            "0038_rename_descripcion_tramoexterno_suministrotramos_plancadena_descripcion_tramo_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="suministrotramos_plancadena",
            name="tipo_tramo",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cadena_app.tipo_transporte",
            ),
        ),
    ]
