# Generated by Django 4.1 on 2023-09-19 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cadena_app", "0039_suministrotramos_plancadena_tipo_tramo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tramos_plancadena",
            name="tipo_transporte",
        ),
        migrations.AddField(
            model_name="midpointemision_plancadena",
            name="suministroTramos_PlanCadena",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cadena_app.suministrotramos_plancadena",
            ),
        ),
    ]
