# Generated by Django 4.1 on 2023-09-24 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadena_app", "0040_remove_tramos_plancadena_tipo_transporte_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="midpointemision_plancadena",
            name="tipo_midpoint",
            field=models.CharField(
                choices=[
                    ("TS", "Tramo Sumininstro"),
                    ("TI", "Tierra"),
                    ("SU", "Suministro"),
                    ("TR", "Tramos"),
                    ("AC", "Actividades"),
                    ("CE", "Consumo de Equipo"),
                ],
                default="SU",
                max_length=2,
            ),
        ),
    ]
