# Generated by Django 4.1 on 2023-05-07 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_producto", models.CharField(max_length=264)),
                ("canal_producto", models.CharField(max_length=264)),
                ("des_producto", models.CharField(max_length=264)),
                ("fec_crea_producto", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="TipoProducto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_tipproducto", models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name="VariacionProducto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku_producto", models.CharField(max_length=264)),
                ("nom_producto", models.CharField(max_length=264)),
                ("pes_producto", models.FloatField()),
                ("lar_producto", models.FloatField()),
                ("anc_producto", models.FloatField()),
                ("prof_producto", models.FloatField()),
                (
                    "prod_asociado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="producto_app.producto",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="producto",
            name="tip_producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="producto_app.tipoproducto",
            ),
        ),
    ]
