# Generated by Django 4.1 on 2023-05-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producto_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="sku_producto",
            field=models.CharField(default=" ", max_length=264),
            preserve_default=False,
        ),
    ]
