# Generated by Django 4.1 on 2023-05-04 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("basic_app", "0002_alter_userprofile_user_rol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="user_rol",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="basic_app.rol"
            ),
        ),
    ]
